apiVersion: v1
description: Mojaloop Helm chart for Kubernetes
name: mojaloop
version: 12.0.0
appVersion: "ml-api-adapter: v11.1.2; central-ledger: v13.0.0; account-lookup-service: v11.1.2; quoting-service: v11.1.4; central-settlement: v12.0.0; central-event-processor: v10.5.0; bulk-api-adapter: v11.0.2; email-notifier: v9.5.0; als-oracle-pathfinder: v10.2.0; transaction-requests-service: v11.1.2; finance-portal-ui: v10.4.0; finance-portal-backend-service: v10.4.0; settlement-management: v8.8.2; operator-settlement: v9.2.1; simulator: v11.0.2; mojaloop-simulator: v11.2.1; sdk-scheme-adapter: v11.10.4; ml-testing-toolkit: v11.5.0 ml-testing-toolkit-ui: v11.5.0; ml-testing-toolkit-cli: v11.3.0"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
