# Default values for central.
# This is a YAML-formatted file.
# Declare global configurations
global: {}

# Declare variables to be passed into your templates.

testrunner:
  enabled: false
  image:
    repository: mojaloop/test-runner
    tag: v0.1
    pullPolicy: Always

  ## Ref: https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies
  deletePolicy: before-hook-creation

  cases: []
    ### Example
    ## - name: setup-hub
    ##   collection: https://raw.githubusercontent.com/mojaloop/postman/master/MojaloopHub_Setup.postman_collection.json
    ##   environment: https://raw.githubusercontent.com/mojaloop/postman/master/environments/Mojaloop-Local-MojaSims.postman_environment.json
    ##   delay: 100
