{{- if .Values.scheduling.enabled }}
apiVersion: {{ template "ml-testing-toolkit-cli.apiVersion.CronJob" . }}
kind: CronJob
metadata:
  name: {{ template "ml-testing-toolkit-cli.fullname" . }}
spec:
  schedule: {{ .Values.scheduling.cronSchedule | quote }}
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  jobTemplate:
  {{ include "ttkCLI.jobTemplate" . | indent 2 }}
{{- else if not .Values.tests.enabled }}
apiVersion: {{ template "ml-testing-toolkit-cli.apiVersion.Job" . }}
kind: Job
metadata:
  name: {{ template "ml-testing-toolkit-cli.fullname" . }}
  {{- if .Values.postInstallHook.enabled }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": {{ .Values.postInstallHook.weight | quote }}
    "helm.sh/hook-delete-policy": {{ .Values.postInstallHook.deletePolicy }}
  {{- end }}
{{ include "ttkCLI.jobTemplate" . }}
{{- end }}
