apiVersion: v1
description: Central-Settlement TransferSettlement Helm chart for Kubernetes
name: centralsettlement-handler-transfersettlement
version: 12.0.0
appVersion: "12.0.0"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
maintainers:
  - name: Miguel de Barros
    email: miguel.debarros@modusbox.com
  - name: Valentin Genev
    email: valentin.genev@modusbox.com
